import puppeteer from 'puppeteer-core';
const sleep = ms => new Promise(r => setTimeout(r, ms));
const browser = await puppeteer.launch({ executablePath: '/usr/bin/google-chrome', headless: 'new', args: ['--no-sandbox'] });
const page = await browser.newPage();
const errors = [];
page.on('pageerror', e => errors.push('PAGEERROR: ' + e.message));
await page.goto('http://127.0.0.1:8000/login', { waitUntil: 'networkidle0' });
await page.type('input[name="email"]', 'matheus2vandrade@gmail.com');
await page.type('input[name="password"]', 'Carpediem1996#');
await Promise.all([page.waitForNavigation({ waitUntil: 'networkidle0' }), page.click('button[type="submit"]')]);
await page.goto('http://127.0.0.1:8000/lancamentos/create', { waitUntil: 'networkidle0' });
await sleep(700);

await page.click('#tipo-receita');
await sleep(1000);
await page.type('input[wire\\:model="descricao"]', 'TESTE RECEITA PERIODO');
await page.type('input[placeholder="R$ 0,00"]', '3100');
await sleep(700);
await page.select('#categoria_id', '25');
await page.click('#rep-periodo');
await sleep(1000);
await page.type('input[wire\\:model="data_fim"]', '2026-11-10');
await page.click('input[wire\\:model="descricao"]');
await sleep(1000);
const valorField = await page.evaluate(() => document.querySelector('input[placeholder="R$ 0,00"]').value);
console.log('campo valor ao salvar:', valorField);
await page.click('button[type="submit"]');
await page.waitForNavigation({ waitUntil: 'networkidle0' }).catch(() => {});
await sleep(1500);
console.log('url final:', page.url());
console.log('erros:', errors.length ? errors.join('\n') : 'nenhum');
await browser.close();
